WeaponCategory.create(name: 'シューター')
WeaponCategory.create(name: 'ブラスター')
WeaponCategory.create(name: 'ローラー')
WeaponCategory.create(name: 'フデ')
WeaponCategory.create(name: 'チャージャー')
WeaponCategory.create(name: 'スロッシャー')
WeaponCategory.create(name: 'スピナー')
WeaponCategory.create(name: 'マニューバー')
WeaponCategory.create(name: 'シェルター')

SubWeapon.create(name: 'スプラッシュボム', image: 'splat_bomb.png')
SubWeapon.create(name: 'キューバンボム', image: 'suction_bomb.png')
SubWeapon.create(name: 'クイックボム', image: 'burst_bomb.png')
SubWeapon.create(name: 'カーリングボム', image: 'curling_bomb.png')
SubWeapon.create(name: 'ロボットボム', image: 'autobomb.png')
SubWeapon.create(name: 'トラップ', image: 'ink_mine.png')
SubWeapon.create(name: 'ポイズンミスト', image: 'toxic_mist.png')
SubWeapon.create(name: 'ポイントセンサー', image: 'point_sensor.png')
SubWeapon.create(name: 'スプラッシュシールド', image: 'splash_wall.png')
SubWeapon.create(name: 'ジャンプビーコン', image: 'squid_beakon.png')
SubWeapon.create(name: 'スプリンクラー', image: 'sprinkler.png')
SubWeapon.create(name: 'タンサンボム', image: 'fizzy_bomb.png')
SubWeapon.create(name: 'トーピード', image: 'torpedo.png')

SpecialWeapon.create(name: 'マルチミサイル', image: 'tenta_missiles.png')
SpecialWeapon.create(name: 'ハイパープレッサー', image: 'sting_ray.png')
SpecialWeapon.create(name: 'ジェットパック', image: 'inkjet.png')
SpecialWeapon.create(name: 'スーパーチャクチ', image: 'splashdown.png')
SpecialWeapon.create(name: 'インクアーマー', image: 'ink_armor.png')
SpecialWeapon.create(name: 'スプラッシュボムピッチャー', image: 'splat_bomb_launcher.png')
SpecialWeapon.create(name: 'キューバンボムピッチャー', image: 'suction_bomb_launcher.png')
SpecialWeapon.create(name: 'クイックボムピッチャー', image: 'burst_bomb_launcher.png')
SpecialWeapon.create(name: 'カーリングボムピッチャー', image: 'curling_bomb_launcher.png')
SpecialWeapon.create(name: 'ロボットボムピッチャー', image: 'autobomb_launcher.png')
SpecialWeapon.create(name: 'アメフラシ', image: 'ink_storm.png')
SpecialWeapon.create(name: 'イカスフィア', image: 'baller.png')
SpecialWeapon.create(name: 'バブルランチャー', image: 'bubble_blower.png')
SpecialWeapon.create(name: 'ナイスダマ', image: 'booyah_bomb.png')
SpecialWeapon.create(name: 'ウルトラハンコ', image: 'ultra_stamp.png')

MainWeapon.create(name: 'ボールドマーカー', image: 'sploosh-o-matic.png', weapon_category_id: 1, sub_weapon_id: 4, special_weapon_id: 4)
MainWeapon.create(name: 'ボールドマーカーネオ', image: 'neo_sploosh-o-matic.png', weapon_category_id: 1, sub_weapon_id: 10, special_weapon_id: 1)
MainWeapon.create(name: 'ボールドマーカー7', image: 'sploosh-o-matic_7.png', weapon_category_id: 1, sub_weapon_id: 1, special_weapon_id: 15)
MainWeapon.create(name: 'わかばシューター', image: 'splattershot_jr.png', weapon_category_id: 1, sub_weapon_id: 1, special_weapon_id: 5)
MainWeapon.create(name: 'もみじシューター', image: 'custom_splattershot_jr.png', weapon_category_id: 1, sub_weapon_id: 5, special_weapon_id: 11)
MainWeapon.create(name: 'おちばシューター', image: 'kensa_splattershot_jr.png', weapon_category_id: 1, sub_weapon_id: 13, special_weapon_id: 13)
MainWeapon.create(name: 'シャープマーカー', image: 'splash-o-matic.png', weapon_category_id: 1, sub_weapon_id: 7, special_weapon_id: 3)
MainWeapon.create(name: 'シャープマーカーネオ', image: 'neo_splash-o-matic.png', weapon_category_id: 1, sub_weapon_id: 3, special_weapon_id: 7)
MainWeapon.create(name: 'プロモデラーMG', image: 'aerospray_mg.png', weapon_category_id: 1, sub_weapon_id: 2, special_weapon_id: 9)
MainWeapon.create(name: 'プロモデラーRG', image: 'aerospray_rg.png', weapon_category_id: 1, sub_weapon_id: 11, special_weapon_id: 12)
MainWeapon.create(name: 'プロモデラーPG', image: 'aerospray_pg.png', weapon_category_id: 1, sub_weapon_id: 3, special_weapon_id: 14)
MainWeapon.create(name: 'スプラシューター', image: 'splattershot.png', weapon_category_id: 1, sub_weapon_id: 3, special_weapon_id: 4)
MainWeapon.create(name: 'スプラシューターコラボ', image: 'tentatek_splattershot.png', weapon_category_id: 1, sub_weapon_id: 1, special_weapon_id: 3)
MainWeapon.create(name: 'スプラシューターベッチュー', image: 'kensa_splattershot.png', weapon_category_id: 1, sub_weapon_id: 2, special_weapon_id: 1)
MainWeapon.create(name: '.52ガロン', image: '52_gal.png', weapon_category_id: 1, sub_weapon_id: 8, special_weapon_id: 12)
MainWeapon.create(name: '.52ガロンデコ', image: '52_gal_deco.png', weapon_category_id: 1, sub_weapon_id: 4, special_weapon_id: 2)
MainWeapon.create(name: '.52ガロンベッチュー', image: 'kensa_52_gal.png', weapon_category_id: 1, sub_weapon_id: 9, special_weapon_id: 14)
MainWeapon.create(name: 'N-ZAP85', image: 'n-zap_85.png', weapon_category_id: 1, sub_weapon_id: 2, special_weapon_id: 5)
MainWeapon.create(name: 'N-ZAP89', image: 'n-zap_89.png', weapon_category_id: 1, sub_weapon_id: 5, special_weapon_id: 1)
MainWeapon.create(name: 'N-ZAP83', image: 'n-zap_83.png', weapon_category_id: 1, sub_weapon_id: 11, special_weapon_id: 11)
MainWeapon.create(name: 'プライムシューター', image: 'splattershot_pro.png', weapon_category_id: 1, sub_weapon_id: 8, special_weapon_id: 11)
MainWeapon.create(name: 'プライムシューターコラボ', image: 'forge_splattershot_pro.png', weapon_category_id: 1, sub_weapon_id: 2, special_weapon_id: 13)
MainWeapon.create(name: 'プライムシューターベッチュー', image: 'kensa_splattershot_pro.png', weapon_category_id: 1, sub_weapon_id: 1, special_weapon_id: 14)
MainWeapon.create(name: '.96ガロン', image: '96_gal.png', weapon_category_id: 1, sub_weapon_id: 11, special_weapon_id: 5)
MainWeapon.create(name: '.96ガロンデコ', image: '96_gal_deco.png', weapon_category_id: 1, sub_weapon_id: 9, special_weapon_id: 3)
MainWeapon.create(name: 'ジェットスイーパー', image: 'jet_squelcher.png', weapon_category_id: 1, sub_weapon_id: 7, special_weapon_id: 1)
MainWeapon.create(name: 'ジェットスイーパーカスタム', image: 'custom_jet_squelcher.png', weapon_category_id: 1, sub_weapon_id: 3, special_weapon_id: 2)
MainWeapon.create(name: 'ノヴァブラスター', image: 'luna_blaster.png', weapon_category_id: 2, sub_weapon_id: 1, special_weapon_id: 12)
MainWeapon.create(name: 'ノヴァブラスターネオ', image: 'luna_blaster_neo.png', weapon_category_id: 2, sub_weapon_id: 6, special_weapon_id: 7)
MainWeapon.create(name: 'ノヴァブラスターベッチュー', image: 'kensa_luna_blaster.png', weapon_category_id: 2, sub_weapon_id: 12, special_weapon_id: 11)
MainWeapon.create(name: 'ホットブラスター', image: 'blaster.png', weapon_category_id: 2, sub_weapon_id: 7, special_weapon_id: 4)
MainWeapon.create(name: 'ホットブラスターカスタム', image: 'custom_blaster.png', weapon_category_id: 2, sub_weapon_id: 5, special_weapon_id: 3)
MainWeapon.create(name: 'ロングブラスター', image: 'range_blaster.png', weapon_category_id: 2, sub_weapon_id: 2, special_weapon_id: 11)
MainWeapon.create(name: 'ロングブラスターカスタム', image: 'custom_range_blaster.png', weapon_category_id: 2, sub_weapon_id: 4, special_weapon_id: 13)
MainWeapon.create(name: 'ロングブラスターネクロ', image: 'grim_range_blaster.png', weapon_category_id: 2, sub_weapon_id: 3, special_weapon_id: 1)
MainWeapon.create(name: 'クラッシュブラスター', image: 'clash_blaster.png', weapon_category_id: 2, sub_weapon_id: 1, special_weapon_id: 2)
MainWeapon.create(name: 'クラッシュブラスターネオ', image: 'clash_blaster_neo.png', weapon_category_id: 2, sub_weapon_id: 4, special_weapon_id: 1)
MainWeapon.create(name: 'ラピッドブラスター', image: 'rapid_blaster.png', weapon_category_id: 2, sub_weapon_id: 6, special_weapon_id: 6)
MainWeapon.create(name: 'ラピッドブラスターデコ', image: 'rapid_blaster_deco.png', weapon_category_id: 2, sub_weapon_id: 2, special_weapon_id: 3)
MainWeapon.create(name: 'ラピッドブラスターベッチュー', image: 'kensa_rapid_blaster.png', weapon_category_id: 2, sub_weapon_id: 13, special_weapon_id: 12)
MainWeapon.create(name: 'Rブラスターエリート', image: 'rapid_blaster_pro.png', weapon_category_id: 2, sub_weapon_id: 7, special_weapon_id: 11)
MainWeapon.create(name: 'Rブラスターエリートデコ', image: 'rapid_blaster_pro_deco.png', weapon_category_id: 2, sub_weapon_id: 9, special_weapon_id: 5)
MainWeapon.create(name: 'L3リールガン', image: 'l-3_nozzlenose.png', weapon_category_id: 1, sub_weapon_id: 4, special_weapon_id: 12)
MainWeapon.create(name: 'L3リールガンD', image: 'l-3_nozzlenose_d.png', weapon_category_id: 1, sub_weapon_id: 3, special_weapon_id: 3)
MainWeapon.create(name: 'L3リールガンベッチュー', image: 'kensa_l-3_nozzlenose.png', weapon_category_id: 1, sub_weapon_id: 9, special_weapon_id: 15)
MainWeapon.create(name: 'H3リールガン', image: 'h-3_nozzlenose.png', weapon_category_id: 1, sub_weapon_id: 8, special_weapon_id: 1)
MainWeapon.create(name: 'H3リールガンD', image: 'h-3_nozzlenose_d.png', weapon_category_id: 1, sub_weapon_id: 2, special_weapon_id: 5)
MainWeapon.create(name: 'H3リールガンチェリー', image: 'cherry_h-3_nozzlenose.png', weapon_category_id: 1, sub_weapon_id: 9, special_weapon_id: 13)
MainWeapon.create(name: 'ボトルガイザー', image: 'squeezer.png', weapon_category_id: 1, sub_weapon_id: 9, special_weapon_id: 2)
MainWeapon.create(name: 'ボトルガイザーフォイル', image: 'foil_squeezer.png', weapon_category_id: 1, sub_weapon_id: 1, special_weapon_id: 13)
MainWeapon.create(name: 'カーボンローラー', image: 'carbon_roller.png', weapon_category_id: 3, sub_weapon_id: 5, special_weapon_id: 11)
MainWeapon.create(name: 'カーボンローラーデコ', image: 'carbon_roller_deco.png', weapon_category_id: 3, sub_weapon_id: 3, special_weapon_id: 10)
MainWeapon.create(name: 'スプラローラー', image: 'splat_roller.png', weapon_category_id: 3, sub_weapon_id: 4, special_weapon_id: 4)
MainWeapon.create(name: 'スプラローラーコラボ', image: 'krak-on_splat_roller.png', weapon_category_id: 3, sub_weapon_id: 10, special_weapon_id: 12)
MainWeapon.create(name: 'スプラローラーベッチュー', image: 'kensa_splat_roller.png', weapon_category_id: 3, sub_weapon_id: 1, special_weapon_id: 13)
MainWeapon.create(name: 'ダイナモローラー', image: 'dynamo_roller.png', weapon_category_id: 3, sub_weapon_id: 6, special_weapon_id: 2)
MainWeapon.create(name: 'ダイナモローラーテスラ', image: 'gold_dynamo_roller.png', weapon_category_id: 3, sub_weapon_id: 1, special_weapon_id: 5)
MainWeapon.create(name: 'ダイナモローラーベッチュー', image: 'kensa_dynamo_roller.png', weapon_category_id: 3, sub_weapon_id: 11, special_weapon_id: 14)
MainWeapon.create(name: 'ヴァリアブルローラー', image: 'flingza_roller.png', weapon_category_id: 3, sub_weapon_id: 9, special_weapon_id: 6)
MainWeapon.create(name: 'ヴァリアブルローラーフォイル', image: 'foil_flingza_roller.png', weapon_category_id: 3, sub_weapon_id: 2, special_weapon_id: 1)
MainWeapon.create(name: 'パブロ', image: 'inkbrush.png', weapon_category_id: 4, sub_weapon_id: 1, special_weapon_id: 4)
MainWeapon.create(name: 'パブロ・ヒュー', image: 'inkbrush_nouveau.png', weapon_category_id: 4, sub_weapon_id: 6, special_weapon_id: 12)
MainWeapon.create(name: 'パーマネント・パブロ', image: 'permanent_inkbrush.png', weapon_category_id: 4, sub_weapon_id: 11, special_weapon_id: 5)
MainWeapon.create(name: 'ホクサイ', image: 'octobrush.png', weapon_category_id: 4, sub_weapon_id: 5, special_weapon_id: 3)
MainWeapon.create(name: 'ホクサイ・ヒュー', image: 'octobrush_nouveau.png', weapon_category_id: 4, sub_weapon_id: 10, special_weapon_id: 1)
MainWeapon.create(name: 'ホクサイベッチュー', image: 'kensa_octobrush.png', weapon_category_id: 4, sub_weapon_id: 2, special_weapon_id: 15)
MainWeapon.create(name: 'スクイックリンα', image: 'classic_squiffer.png', weapon_category_id: 5, sub_weapon_id: 8, special_weapon_id: 5)
MainWeapon.create(name: 'スクイックリンβ', image: 'new_squiffer.png', weapon_category_id: 5, sub_weapon_id: 5, special_weapon_id: 12)
MainWeapon.create(name: 'スクイックリンγ', image: 'fresh_squiffer.png', weapon_category_id: 5, sub_weapon_id: 2, special_weapon_id: 3)
MainWeapon.create(name: 'スプラチャージャー', image: 'splat_charger.png', weapon_category_id: 5, sub_weapon_id: 1, special_weapon_id: 2)
MainWeapon.create(name: 'スプラチャージャーコラボ', image: 'firefin_splat_charger.png', weapon_category_id: 5, sub_weapon_id: 9, special_weapon_id: 7)
MainWeapon.create(name: 'スプラチャージャーベッチュー', image: 'kensa_splat_charger.png', weapon_category_id: 5, sub_weapon_id: 11, special_weapon_id: 12)
MainWeapon.create(name: 'スプラスコープ', image: 'splatterscope.png', weapon_category_id: 5, sub_weapon_id: 1, special_weapon_id: 2)
MainWeapon.create(name: 'スプラスコープコラボ', image: 'firefin_splatterscope.png', weapon_category_id: 5, sub_weapon_id: 9, special_weapon_id: 7)
MainWeapon.create(name: 'スプラスコープベッチュー', image: 'kensa_splatterscope.png', weapon_category_id: 5, sub_weapon_id: 11, special_weapon_id: 12)
MainWeapon.create(name: 'リッター4K', image: 'e-liter_4k.png', weapon_category_id: 5, sub_weapon_id: 6, special_weapon_id: 11)
MainWeapon.create(name: 'リッター4Kカスタム', image: 'custom_e-liter_4k.png', weapon_category_id: 5, sub_weapon_id: 10, special_weapon_id: 13)
MainWeapon.create(name: '4Kスコープ', image: 'e-liter_4k_scope.png', weapon_category_id: 5, sub_weapon_id: 6, special_weapon_id: 11)
MainWeapon.create(name: '4Kスコープカスタム', image: 'custom_e-liter_4k_scope.png', weapon_category_id: 5, sub_weapon_id: 10, special_weapon_id: 13)
MainWeapon.create(name: '14式竹筒銃・甲', image: 'bamboozler_14_mk_1.png', weapon_category_id: 5, sub_weapon_id: 4, special_weapon_id: 1)
MainWeapon.create(name: '14式竹筒銃・乙', image: 'bamboozler_14_mk_2.png', weapon_category_id: 5, sub_weapon_id: 7, special_weapon_id: 8)
MainWeapon.create(name: '14式竹筒銃・丙', image: 'bamboozler_14_mk_3.png', weapon_category_id: 5, sub_weapon_id: 12, special_weapon_id: 13)
MainWeapon.create(name: 'ソイチューバー', image: 'goo_tuber.png', weapon_category_id: 5, sub_weapon_id: 2, special_weapon_id: 4)
MainWeapon.create(name: 'ソイチューバーカスタム', image: 'custom_goo_tuber.png', weapon_category_id: 5, sub_weapon_id: 4, special_weapon_id: 3)
MainWeapon.create(name: 'バケットスロッシャー', image: 'slosher.png', weapon_category_id: 6, sub_weapon_id: 2, special_weapon_id: 1)
MainWeapon.create(name: 'バケットスロッシャーデコ', image: 'slosher_deco.png', weapon_category_id: 6, sub_weapon_id: 11, special_weapon_id: 12)
MainWeapon.create(name: 'バケットスロッシャーソーダ', image: 'slosher_soda.png', weapon_category_id: 6, sub_weapon_id: 1, special_weapon_id: 8)
MainWeapon.create(name: 'ヒッセン', image: 'tri-slosher.png', weapon_category_id: 6, sub_weapon_id: 3, special_weapon_id: 5)
MainWeapon.create(name: 'ヒッセン・ヒュー', image: 'tri-slosher_nouveau.png', weapon_category_id: 6, sub_weapon_id: 1, special_weapon_id: 11)
MainWeapon.create(name: 'スクリュースロッシャー', image: 'sloshing_machine.png', weapon_category_id: 6, sub_weapon_id: 5, special_weapon_id: 2)
MainWeapon.create(name: 'スクリュースロッシャーネオ', image: 'sloshing_machine_neo.png', weapon_category_id: 6, sub_weapon_id: 8, special_weapon_id: 6)
MainWeapon.create(name: 'スクリュースロッシャーベッチュー', image: 'kensa_sloshing_machine.png', weapon_category_id: 6, sub_weapon_id: 12, special_weapon_id: 4)
MainWeapon.create(name: 'オーバーフロッシャー', image: 'bloblobber.png', weapon_category_id: 6, sub_weapon_id: 9, special_weapon_id: 11)
MainWeapon.create(name: 'オーバーフロッシャーデコ', image: 'bloblobber_deco.png', weapon_category_id: 6, sub_weapon_id: 11, special_weapon_id: 7)
MainWeapon.create(name: 'エクスプロッシャー', image: 'explosher.png', weapon_category_id: 6, sub_weapon_id: 11, special_weapon_id: 13)
MainWeapon.create(name: 'エクスプロッシャーカスタム', image: 'custom_explosher.png', weapon_category_id: 6, sub_weapon_id: 8, special_weapon_id: 12)
MainWeapon.create(name: 'スプラスピナー', image: 'mini_splatling.png', weapon_category_id: 7, sub_weapon_id: 3, special_weapon_id: 1)
MainWeapon.create(name: 'スプラスピナーコラボ', image: 'zink_mini_splatling.png', weapon_category_id: 7, sub_weapon_id: 4, special_weapon_id: 11)
MainWeapon.create(name: 'スプラスピナーベッチュー', image: 'kensa_mini_splatling.png', weapon_category_id: 7, sub_weapon_id: 7, special_weapon_id: 15)
MainWeapon.create(name: 'バレルスピナー', image: 'heavy_splatling.png', weapon_category_id: 7, sub_weapon_id: 11, special_weapon_id: 2)
MainWeapon.create(name: 'バレルスピナーデコ', image: 'heavy_splatling_deco.png', weapon_category_id: 7, sub_weapon_id: 9, special_weapon_id: 13)
MainWeapon.create(name: 'バレルスピナーリミックス', image: 'heavy_splatling_remix.png', weapon_category_id: 7, sub_weapon_id: 8, special_weapon_id: 14)
MainWeapon.create(name: 'ハイドラント', image: 'hydra_splatling.png', weapon_category_id: 7, sub_weapon_id: 5, special_weapon_id: 4)
MainWeapon.create(name: 'ハイドラントカスタム', image: 'custom_hydra_splatling.png', weapon_category_id: 7, sub_weapon_id: 6, special_weapon_id: 5)
MainWeapon.create(name: 'クーゲルシュライバー', image: 'ballpoint_splatling.png', weapon_category_id: 7, sub_weapon_id: 7, special_weapon_id: 3)
MainWeapon.create(name: 'クーゲルシュライバー・ヒュー', image: 'ballpoint_splatling_nouveau.png', weapon_category_id: 7, sub_weapon_id: 10, special_weapon_id: 11)
MainWeapon.create(name: 'ノーチラス47', image: 'nautilus_47.png', weapon_category_id: 7, sub_weapon_id: 8, special_weapon_id: 12)
MainWeapon.create(name: 'ノーチラス79', image: 'nautilus_79.png', weapon_category_id: 7, sub_weapon_id: 2, special_weapon_id: 3)
MainWeapon.create(name: 'スパッタリー', image: 'dapple_dualies.png', weapon_category_id: 8, sub_weapon_id: 10, special_weapon_id: 7)
MainWeapon.create(name: 'スパッタリー・ヒュー', image: 'dapple_dualies_nouveau.png', weapon_category_id: 8, sub_weapon_id: 7, special_weapon_id: 11)
MainWeapon.create(name: 'スパッタリークリア', image: 'clear_dapple_dualies.png', weapon_category_id: 8, sub_weapon_id: 13, special_weapon_id: 4)
MainWeapon.create(name: 'スプラマニューバー', image: 'splat_dualies.png', weapon_category_id: 8, sub_weapon_id: 3, special_weapon_id: 1)
MainWeapon.create(name: 'スプラマニューバーコラボ', image: 'enperry_splat_dualies.png', weapon_category_id: 8, sub_weapon_id: 4, special_weapon_id: 3)
MainWeapon.create(name: 'スプラマニューバーベッチュー', image: 'kensa_splat_dualies.png', weapon_category_id: 8, sub_weapon_id: 2, special_weapon_id: 12)
MainWeapon.create(name: 'ケルビン525', image: 'glooga_dualies.png', weapon_category_id: 8, sub_weapon_id: 6, special_weapon_id: 3)
MainWeapon.create(name: 'ケルビン525デコ', image: 'glooga_dualies_deco.png', weapon_category_id: 8, sub_weapon_id: 9, special_weapon_id: 12)
MainWeapon.create(name: 'ケルビン525ベッチュー', image: 'kensa_glooga_dualies.png', weapon_category_id: 8, sub_weapon_id: 12, special_weapon_id: 5)
MainWeapon.create(name: 'デュアルスイーパー', image: 'dualie_squelchers.png', weapon_category_id: 8, sub_weapon_id: 8, special_weapon_id: 1)
MainWeapon.create(name: 'デュアルスイーパーカスタム', image: 'custom_dualie_squelchers.png', weapon_category_id: 8, sub_weapon_id: 1, special_weapon_id: 11)
MainWeapon.create(name: 'クアッドホッパーブラック', image: 'dark_tetra_dualies.png', weapon_category_id: 8, sub_weapon_id: 5, special_weapon_id: 4)
MainWeapon.create(name: 'クアッドホッパーホワイト', image: 'light_tetra_dualies.png', weapon_category_id: 8, sub_weapon_id: 11, special_weapon_id: 10)
MainWeapon.create(name: 'パラシェルター', image: 'splat_brella.png', weapon_category_id: 9, sub_weapon_id: 11, special_weapon_id: 11)
MainWeapon.create(name: 'パラシェルターソレーラ', image: 'sorella_brella.png', weapon_category_id: 9, sub_weapon_id: 5, special_weapon_id: 6)
MainWeapon.create(name: 'キャンピングシェルター', image: 'tenta_brella.png', weapon_category_id: 9, sub_weapon_id: 10, special_weapon_id: 13)
MainWeapon.create(name: 'キャンピングシェルターソレーラ', image: 'tenta_sorella_brella.png', weapon_category_id: 9, sub_weapon_id: 9, special_weapon_id: 9)
MainWeapon.create(name: 'キャンピングシェルターカーモ', image: 'tenta_camo_brella.png', weapon_category_id: 9, sub_weapon_id: 6, special_weapon_id: 15)
MainWeapon.create(name: 'スパイガジェット', image: 'undercover_brella.png', weapon_category_id: 9, sub_weapon_id: 6, special_weapon_id: 4)
MainWeapon.create(name: 'スパイガジェットソレーラ', image: 'undercover_sorella_brella.png', weapon_category_id: 9, sub_weapon_id: 1, special_weapon_id: 12)
MainWeapon.create(name: 'スパイガジェットベッチュー', image: 'kensa_undercover_brella.png', weapon_category_id: 9, sub_weapon_id: 13, special_weapon_id: 5)

Stage.create(name: 'バッテラストリート', image: 'the_reef.jpg')
Stage.create(name: 'フジツボスポーツクラブ', image: 'musselforge_fitness.jpg')
Stage.create(name: 'ガンガゼ野外音楽堂', image: 'starfish_mainstage.jpg')
Stage.create(name: 'コンブトラック', image: 'humpback_pump_track.jpg')
Stage.create(name: '海女美術大学', image: 'inkblot_art_academy.jpg')
Stage.create(name: 'チョウザメ造船', image: 'sturgeon_shipyard.jpg')
Stage.create(name: 'タチウオパーキング', image: 'moray_towers.jpg')
Stage.create(name: 'ホッケふ頭', image: 'port_mackerel.jpg')
Stage.create(name: 'マンタマリア号', image: 'manta_maria.jpg')
Stage.create(name: 'モズク農園', image: 'kelp_dome.jpg')
Stage.create(name: 'エンガワ河川敷', image: 'snapper_canal.jpg')
Stage.create(name: 'Bバスパーク', image: 'blackberry_skatepark.jpg')
Stage.create(name: 'ザトウマーケット', image: 'mako_mart.jpg')
Stage.create(name: 'ハコフグ倉庫', image: 'walleye_warehouse.jpg')
Stage.create(name: 'デボン海洋博物館', image: 'shellendorf_institute.jpg')
Stage.create(name: 'アロワナモール', image: 'arowana_mall.jpg')
Stage.create(name: 'アジフライスタジアム', image: 'goby_arena.jpg')
Stage.create(name: 'ショッツル鉱山', image: 'piranha_pit.jpg')
Stage.create(name: 'モンガラキャンプ場', image: 'camp_triggerfish.jpg')
Stage.create(name: 'スメーシーワールド', image: 'wahoo_world.jpg')
Stage.create(name: 'ホテルニューオートロ', image: 'new_albacore_hotel.jpg')
Stage.create(name: 'アンチョビットゲームズ', image: 'ancho-v_games.jpg')
Stage.create(name: 'ムツゴ楼', image: 'skipper_pavilion.jpg')

User.create(name: 'Sylpha', email: 'sylpha.games@gmail.com', password: 'sayumi729864')
